# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk17

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
   - CODECOV_TOKEN="483780fa-d6cf-4bfc-b7d4-0e786131b220"

# Отправлять уведомление на почту rogovolod@gmail.com если сборка упала
notifications:
  email:
    recipients:
      -rogovolod@gmail.com
    on_success: never # default: change
    on_failure: always # default: always